name: Deploy app preview
env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
on:
  push:
    branches-ignore:
      - main
      - master
jobs:
  deploy-preview:
    name: preview deployement
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install vercel CLI
        run: npm install --global vercel@canary

      - name: Pull information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_ACCESS_TOKEN }}

      - name: Build app artifact
        run: vercel build --token=${{ secrets.VERCEL_ACCESS_TOKEN }}

      - name: Deploy app artifact
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
