name: build cozy frontend app
on: [push]
jobs:
  lint_and_build:
    name: Lint & build app
    run-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run lint
        run: npm run lint

      - name: Build app
        run: npm run build
